export const developers = [
  {
    name: "Ken Mar Lisondra",
    role: "Full Stack Developer",
    category: "Full Stack",
    skills: ["JavaScript", "React", "Next.js", "Node.js", "Supabase"],
    linkedIn: "https://www.linkedin.com/in/knmr-dev/",
    avatar: "/assets/avatars/kenneth.jpg",
  },
  {
    name: "Rolando Mondilla Jr.",
    role: "Mobile Software Developer",
    category: "Mobile",
    skills: [
      "React Native",
      "Flutter",
      "iOS Development",
      "Android Development",
      "API Integration",
    ],
    linkedIn: "https://www.linkedin.com/in/rolando-mondilla-jr-62a210334/",
    avatar: "/assets/avatars/rolando.jpg",
  },
  {
    name: "Mc Phy Cabanes",
    role: "Frontend Developer",
    category: "Frontend",
    skills: [
      "React",
      "JavaScript",
      "Tailwind CSS",
      "Responsive UI",
      "Component Design",
    ],
    linkedIn: "https://www.linkedin.com/in/mc-phy-cabanes-6b35b31b7/",
    avatar: "/assets/avatars/mcphy.jpg",
  },
  {
    name: "Glywys Claude Igoy",
    role: "Software Developer",
    category: "Backend",
    skills: [
      "JavaScript",
      "Web Development",
      "Debugging",
      "Code Optimization",
      "Problem Solving",
    ],
    linkedIn: "https://www.linkedin.com/in/glywys-claude-igoy-33256826b/",
    avatar: "/assets/avatars/glywys2.jpg",
  },
   {
    name: "Isabela Ayn Deocampo",
    role: "Frontend Developer",
    category: "Frontend",
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Web Accessibility",
    ],
    linkedIn: "https://www.linkedin.com/in/isabela-ayn-deocampo/",
     avatar: "/assets/avatars/Isabela.jpg",
  },
  {
    name: "Michael Jan Arieta",
    role: "Full Stack Developer",
    category: "Full Stack",
    skills: ["Next.js", "Supabase", "REST APIs", "Automation"],
    linkedIn: "https://www.linkedin.com/in/michael-jan-arieta-a8b30a242/",
    avatar: "/assets/avatars/michael.jpg",
  },
  {
    name: "Caezzy Gayle Sayson",
    role: "Frontend Developer",
    category: "Frontend",
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "UI/UX Design",
      "Responsive Web Design",
    ],
    linkedIn: "https://www.linkedin.com/in/caezzy-gayle-sayson-4503902b0/",
   avatar: "/assets/avatars/Caezzy.jpg",
  },
    {
    name: "Mark John Lagria",
    role: "Backend Developer",
    category: "Backend",
    skills: ["PHP", "Laravel", "REST APIs", "MySQL", "Server-side Logic"],
    linkedIn: "https://www.linkedin.com/in/lagriamj/",
    avatar: "/assets/avatars/mark2.jpg",
  },
 {
  name: "Dahnica Tedlos",
  role: "IT Administrator",
  category: "IT",
  skills: [
    "System Administration",
    "Network Troubleshooting",
    "User Access Management",
    "Hardware & Software Support",
    "IT Infrastructure",
  ],
  linkedIn: "https://www.linkedin.com/in/dahnica-tedlos-b68329268/",
   avatar: "/assets/avatars/Dahnica.jpg",
}
];

export const categories = ["All", "Frontend", "Backend", "Full Stack", "Mobile"];
